---
# tasks file for travis

- name: Install requirements
  ansible.builtin.package:
    name: "{{ travis_requirements }}"
    state: present

- name: Install travis
  community.general.gem:
    name: "{{ travis_package }}"
    state: present
    user_install: no
